Repository TPT-Loane/TPT-Loane, pull requests merged in 2021-05, with the labels that each got.

#61 Add backend lint and build jobs to travisCI
  .travis.yml
Labels: devops

#39 Dockerize FE and BE
  README.md
  be/README.md
  be/db/dev-db/README.md
  be/db/dev-db/docker-compose.yaml
  be/docker/be-dev.dockerfile
  docker-compose.yaml
  docker/.gitignore
  fe/README.md
  fe/docker-compose.yaml
  fe/docker/fe-dev.dockerfile
Labels: devops

#65 DB: Clean up database data migrations (sql folder)
  be/db/README.md
  be/db/dev-db/.gitignore
  be/db/dev-db/README.md
  be/db/dev-db/sql/create_tables.sql
  be/db/dev-db/sql/fill_tables.sql
  docker-compose.yaml
Labels: DB

#73 DOC: Add graph for visualizing the loan process
  README.md
  doc/README.md
  doc/overall-flow-digraph.png
  doc/src/README.md
  doc/src/overall-flow-digraph.gv
Labels: doc

#94 Add apollo client and codegen
  fe/.env.example
  fe/.eslintignore
  fe/codegen.yml
  fe/package-lock.json
  fe/package.json
  fe/src/generated/graphql.tsx
  fe/src/graphql/queries/test.graphql
  fe/src/index.tsx
Labels: FE

#122 Serve fe from be
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/main.ts
Labels: BE, FE

#124 Be fix parent categories new
  be/schema.gql
  be/src/category/category.resolver.ts
  be/src/category/category.service.ts
Labels: BE, bug

#120 Fake db data
  be/.env.example
  be/package-lock.json
  be/package.json
  be/schema.gql
  be/src/app.module.ts
  be/src/category/category.module.ts
  be/src/note/note.module.ts
  be/src/testing/testing.module.ts
  be/src/testing/testing.resolver.ts
  be/src/testing/testing.service.ts
Labels: BE
